ConsomiTounsi.Web/Controllers/DeliveryController.cs
using ConsomiTounsi.Data;
using ConsomiTounsi.Data.Infrastructure;
using ConsomiTousi.Domain;
using ConsomiTousi.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ConsomiTounsi.Web.Controllers
{
    public class DeliveryController : Controller
    {

        IDataBaseFactory dbf;
        IUnitOfWork uow;
        IService<Delivery> deliveryS;
        IService<DeliveryMan> deliveryManS;

        public DeliveryController()
        {
            dbf = new DataBaseFactory();
            uow = new UnitOfWork(dbf);
            deliveryS = new Service<Delivery>(uow);
            deliveryManS=new Service<DeliveryMan>(uow);
        }
        // GET: Delivery
        public ActionResult Index()
        {
            return View(deliveryS.GetAll());
        }

        public ActionResult Validation()
        {
            return View();
        }

        // GET: Delivery/Details/5
        public ActionResult Details(int id)
        {
            return View(deliveryS.GetById(id));
        }

        // GET: Delivery/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Delivery/Create
        [HttpPost]
        public ActionResult Create(Delivery d)
        {
            deliveryS.Add(d);
            deliveryS.Commit();
            return RedirectToAction("Index");
        }

        // GET: Delivery/Edit/5
        public ActionResult Edit(int id)
        {
            return View(deliveryS.GetById(id));
        }

        // POST: Delivery/Edit/5
        [HttpPost]
        public ActionResult Edit(Delivery e)
        {
            try
            {
                // TODO: Add delete logic here
                deliveryS.Update(e);
                deliveryS.Commit();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Delivery/Delete/5
        public ActionResult Delete(int id)
        {
            return View(deliveryS.GetById(id));
        }

        // POST: Delivery/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                deliveryS.Delete(deliveryS.GetById(id));
                deliveryS.Commit();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Confirmer(int id,int Man)
        {
            ConsomiCtxt ctx = new ConsomiCtxt();
            var change= deliveryS.GetById(id);
            var changeM = deliveryManS.GetById(Man);
            if ( changeM.MyDelivery.DeliveryState!="yes")
            {

                change.DeliveryState = "yes";
                changeM.DeliveryId = null;

                int som = int.Parse(changeM.ImageCin_d) + 1;
                changeM.ImageCin_d =som.ToString();  
                
                
                deliveryS.Commit();
                return RedirectToAction("Index", "DeliveryMan");

            }
            else {

                changeM.DeliveryId = null;
                deliveryS.Commit();

                return RedirectToAction("Validation"); }
       

        
    }

        // POST: Delivery/confirmer/5
        [HttpPost]
        public ActionResult Confirmer()
        {
           
            return View();


        }


        //public JsonResult ListDelivery()
        //{
        //    var maplist = deliveryS.GetAll();

        //    return Json(maplist, JsonRequestBehavior.AllowGet);
        //}



    }
}

ConsomiTounsi.Web/Controllers/DeliveryManController.cs
using ConsomiTounsi.Data;
using ConsomiTounsi.Data.Infrastructure;
using ConsomiTousi.Domain;
using ConsomiTousi.Service;
using Postal;
using System.Web.Helpers;
using System.Web.Mvc;

namespace ConsomiTounsi.Web.Controllers
{
    public class DeliveryManController : Controller
    {

        IDataBaseFactory dbf;
        IUnitOfWork uow;
        IService<DeliveryMan> deliveryManS;
        IService<Delivery> serviceD;

        public DeliveryManController()
        {
            dbf = new DataBaseFactory();
            uow = new UnitOfWork(dbf);
            deliveryManS = new Service<DeliveryMan>(uow);
            serviceD = new Service<Delivery>(uow);
        }
        // GET: DeliveryMan
        public ActionResult Index()
        {
            return View(deliveryManS.GetAll());
        }

        public JsonResult ListMap()
        {
           var maplist = deliveryManS.GetAll();
           
            return Json(maplist,JsonRequestBehavior.AllowGet);
        }


        // GET: DeliveryMan/Details/5
        public ActionResult Details(int id)
        {
            return View(deliveryManS.GetById(id));
        }

        // GET: DeliveryMan/Create
        public ActionResult Create()
        {
            ViewBag.DeliveryId = new SelectList(serviceD.GetAll(), "DeliveryId", "DeliveryId");
            return View();
        }

        // POST: DeliveryMan/Create
        [HttpPost]
        public ActionResult Create(DeliveryMan dm)
        {
            deliveryManS.Add(dm);
            deliveryManS.Commit();
            return RedirectToAction("Index");
        }

        // GET: DeliveryMan/Edit/5
        public ActionResult Edit(int id)
        {

            DeliveryMan prod = deliveryManS.GetById(id);
            ViewBag.DeliveryId = new SelectList(serviceD.GetAll(), "DeliveryId", "Ville",prod.DeliveryId);
            //ViewBag.CategoryId = new SelectList(serviceCat.GetAll(), "CategoryId", "Name", prod.CategoryId);
            return View(prod);
        }

        // POST: DeliveryMan/Edit/5
        [HttpPost]
        public ActionResult Edit(DeliveryMan e)
        {

            //var info = deliveryManS.GetById(id);
            dynamic email = new Email("Example");
            email.To = e.UsersEmail_d;
            email.Message = "Connectez-vous pour confirmer";
           email.Send();

            
                deliveryManS.Update(e);
                deliveryManS.Commit();
                

                return RedirectToAction("Index");
          
        }

        // GET: DeliveryMan/Delete/5
        public ActionResult Delete(int id)
        {
            return View(deliveryManS.GetById(id));
        }

        // POST: DeliveryMan/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                deliveryManS.Delete(deliveryManS.GetById(id));
                deliveryManS.Commit();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ConfirmerMan(int id)
        {
            ConsomiCtxt ctx = new ConsomiCtxt();
            var change = deliveryManS.GetById(id);
            change.DeliveryId=null;
           

            deliveryManS.Commit();
            return RedirectToAction("Index");
        }


        public ActionResult AffecterLivraison(int id)
        {
            ViewBag.DeliveryId = new SelectList(serviceD.GetAll(), "DeliveryId", "DeliveryId");
            
            return View(deliveryManS.GetById(id));
        }

        // POST: DeliveryMan/Edit/5
        [HttpPost]
        public ActionResult AffecterLivraison(DeliveryMan e)
        {
            try
            {
                // TODO: Add delete logic here
                deliveryManS.Update(e);
                deliveryManS.Commit();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Chart()
        {

            
            var change = deliveryManS.GetAll();
           

            foreach (var p in change)
            { 


                var a = int.Parse(p.ImageCin_d);
                var b = p.UsersName_d;

                new Chart(width: 800, height: 280)


               .AddSeries(
                          chartType: "column",
                          xValue: new[] { b },
                          yValues: new[] { a }).Write("png");

            }

                return null ;
            
           
        }

    }
}

ConsomiTounsi.Web/Views/DeliveryMan/AffecterLivraison.cshtml
@model ConsomiTousi.Domain.DeliveryMan

@{
    ViewBag.Title = "AffecterLivraison";
}

<h2>edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DeliveryManId)

        <div class="form-group">
            <label>Titre</label>
            @*@Html.LabelFor(model => model.UsersName_d, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.EditorFor(model => model.UsersName_d, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UsersName_d, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Nom</label>
            @*@Html.LabelFor(model => model.UsersLastname_d, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.EditorFor(model => model.UsersLastname_d, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UsersLastname_d, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Email</label>
            @*@Html.LabelFor(model => model.UsersEmail_d, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.EditorFor(model => model.UsersEmail_d, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UsersEmail_d, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Description</label>
            @*@Html.LabelFor(model => model.UsersCin_d, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.EditorFor(model => model.UsersCin_d, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UsersCin_d, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Adresse</label>
            @*@Html.LabelFor(model => model.UsersAdress_d, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.EditorFor(model => model.UsersAdress_d, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UsersAdress_d, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.DateRegister_d, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateRegister_d, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateRegister_d, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.DateNaissance_d, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateNaissance_d, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateNaissance_d, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pays_d, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pays_d, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pays_d, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ville_d, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Ville_d, new { htmlAttributes = new { @class = "form-control" } })*@
                @{
                    List<SelectListItem> listItems = new List<SelectListItem>();
                    listItems.Add(new SelectListItem
                    {
                        Text = "tunis",
                        Value = "tunis",
                        Selected = false
                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "sousse",
                        Value = "sousse"

                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "nabeul",
                        Value = "nabeul"
                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "hamamet",
                        Value = "hamamet"
                    });
                }

                @Html.DropDownListFor(model => model.Ville_d, listItems, "-- Select Ville --")
                @Html.ValidationMessageFor(model => model.Ville_d, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State_d, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State_d, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State_d, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone_d, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone_d, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone_d, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.ImageCin_d, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageCin_d, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageCin_d, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.lng, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lng, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lng, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group"hidden>
            @Html.LabelFor(model => model.ing, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ing, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ing, "", new { @class = "text-danger" })
            </div>
        </div>


   
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
                    }




<script src="~/Scripts/jquery-3.2.1.js" type="text/javascript"></script>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

<script type="text/javascript">


    $("#Ville_d").mouseup(function () {

        var str = $("#Ville_d").val();

        console.log(str);
        if (str == "tunis") {
            var ingtu = "36,8188";
            var lngtu = "10,166";
            $('#ing').val(ingtu);
            $('#lng').val(lngtu);
            //$('p').prepend('<strong>Texte inséré avant le contenu actuel.</strong> ');

        }

        if (str == "sousse") {
            var ingS = "35,833";
            var lngS = "10,6387";
            $('#ing').val(ingS);
            $('#lng').val(lngS);
        }
        if (str == "nabeul") {
            var ingN = "36,4542";
            var lngN = "10,7347";
            $('#ing').val(ingN);
            $('#lng').val(lngN);
        }

        if (str == "hamamet") {
            var ingH = "36,4";
            var lngH = "10,6167";
            $('#ing').val(ingH);
            $('#lng').val(lngH);
        }
    });




</script>

ConsomiTounsi.Web/Views/DeliveryMan/Chart.cshtml
@{
    ViewBag.Title = "Chart";
}

<h2>Chart</h2>

<di>

    <img src="@Url.Action("Chart")" alt="SimpleChart"/>
</di>

ConsomiTounsi.Web/Views/DeliveryMan/ConfirmerMan.cshtml
@{
    ViewBag.Title = "ConfirmerMan";
}

<h2>ConfirmerMan</h2>

ConsomiTounsi.Web/Views/DeliveryMan/Delete.cshtml
@model ConsomiTousi.Domain.DeliveryMan

@{
    ViewBag.Title = "Delete";
}


<div>

<div class="row">
    <div class="col-lg-12">
        <div class="white-box">
            <div class="">

                <hr>
                <div class="row">


                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <h3 class="box-title m-t-40">Are you sure you want to delete this?</h3>
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td width="390">Titre</td>
                                        <td> @Html.DisplayFor(model => model.UsersName_d) </td>
                                    </tr>
                                    <tr>
                                        <td>Nom</td>
                                        <td>@Html.DisplayFor(model => model.UsersLastname_d)</td>
                                    </tr>
                                    <tr>
                                        <td>Email</td>
                                        <td> @Html.DisplayFor(model => model.UsersEmail_d) </td>
                                    </tr>
                                    <tr>
                                        <td>Phone</td>
                                        <td>@Html.DisplayFor(model => model.Phone_d)</td>
                                    </tr>
                                    <tr>
                                        <td>Description</td>
                                        <td>@Html.DisplayFor(model => model.UsersCin_d) </td>
                                    </tr>
                                    <tr>
                                        <td>Adresse</td>
                                        <td>@Html.DisplayFor(model => model.UsersAdress_d)</td>
                                    </tr>
                                    <tr>
                                        <td>Ville</td>
                                        <td> @Html.DisplayFor(model => model.Ville_d) </td>
                                    </tr>
                                    <tr>
                                        <td>Pays</td>
                                        <td> @Html.DisplayFor(model => model.Pays_d) </td>
                                    </tr>
                                    <tr>
                                        <td>Etat</td>
                                        <td>@Html.DisplayFor(model => model.State_d)</td>
                                    </tr>
                                    <tr>
                                        <td>Latitude</td>
                                        <td> @Html.DisplayFor(model => model.ing) </td>
                                    </tr>
                                    <tr>
                                        <td>Longitude</td>
                                        <td>@Html.DisplayFor(model => model.lng)</td>
                                    </tr>


                                   

                                </tbody>
                            </table>
                            <p>

                                
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--row -->
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ConsomiTounsi.Web/Views/DeliveryMan/Index.cshtml
@model IEnumerable<ConsomiTousi.Domain.DeliveryMan>

@{
    ViewBag.Title = "Index";

}

<h2>Les Annonces</h2>


<!-- row -->
<div class="row">
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
        <div class="white-box">
            <p>
                @Html.ActionLink("Ajouter Annonce", "Create")
            </p>

            <p>
                <input type="text" name="category" id="search" placeholder="chercher">
            </p>
            <div class="table-responsive">
                <table class="table product-overview" id="contenu">
                    <thead id="filter">
                        <tr>
                            <th>Titre</th>
                            <th>Nom</th>
                            <th>Etat</th>
                            <th>Description</th>
                            <th>Phone</th>
                            <th>Email</th>
                            <th>Ville</th>
                            <th>RDV</th>
                            <th>Date</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    @foreach (var item in Model)
                    {

                        <tbody>
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.UsersName_d)</td>
                                <td>@Html.DisplayFor(modelItem => item.UsersLastname_d)</td>
                                <td>
                                    <span class="label label-success font-weight-100"> @Html.DisplayFor(modelItem => item.State_d)</span>
                                </td>
                                <td>@Html.DisplayFor(modelItem => item.UsersCin_d)</td>
                                <td>@Html.DisplayFor(modelItem => item.Phone_d)</td>
                                <td>@Html.DisplayFor(modelItem => item.UsersEmail_d)</td>
                                <td>@Html.DisplayFor(modelItem => item.Ville_d)</td>

                                <td>
                                    <span class="label label-success font-weight-100">
                                        @Html.DisplayFor(modelItem => item.DeliveryId)
                                    </span>
                                    <input type="text" size="1" id="details" name="details" value="@Html.DisplayFor(modelItem => item.DeliveryId)" hidden />
                                    @*<input type="button" value="Detail" onclick="recup();">*@
                                </td>



                                <td>
                                    @Html.DisplayFor(modelItem => item.DateRegister_d)
                                </td>
                                @if (item.State_d != "disponible")
                                {
                                    <td>


                                        @Html.ActionLink("Delete", "Delete", new { id = item.DeliveryManId })|
                                        @Html.ActionLink("Details", "Details", new { id = item.DeliveryManId })`|
                                        @Html.ActionLink("disponible", "Details", new { id = item.DeliveryManId })`



                                    </td>

                                }
                                else
                                {
                                    <td>
                                        @Html.ActionLink("Affecter", "Edit", new { id = item.DeliveryManId })|
                                        @Html.ActionLink("Edit", "AffecterLivraison", new { id = item.DeliveryManId })|

                                        @Html.ActionLink("Delete", "Delete", new { id = item.DeliveryManId })|
                                        @Html.ActionLink("Details", "Details", new { id = item.DeliveryManId })`|
                                        @Html.ActionLink("Confirmer", "Confirmer", "Delivery", new { id = item.DeliveryId, Man = item.DeliveryManId }, null)|


                                    </td>
                                }


                            </tr>

                        </tbody>

                    }
                </table>
            </div>
        </div>
    </div>
</div>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Google Map</title>
    <style>
        #map {
            height: 400px;
            width: 100%;
        }
    </style>
</head>
<body>
    <h1>My Google Map</h1>
    <div id="map"></div>
</body>
</html>
<script src="~/Scripts/jquery-3.2.1.js" type="text/javascript"></script>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

<script type="text/javascript">
    
    var hot;
    function intialisation() {


      

      

        $.getJSON('http://localhost:40740/DeliveryMan/ListMap', function (data) {
            hot = data;

        })
        setTimeout(function () {
           
            console.log("okkkkkk" + hot);
           
            initMap();
        }, 3000);
        
        //$.ajax({
        //    type: "GET",
        //    url: "http://localhost:40740/DeliveryMan/ListMap",


        //    dataType: "json",

        //    success: function (data) {
        //        hot = data;
        //        console.log("okkkkkk" + hot);
        //        alert(hot[0].UsersName_d);

        //        initMap();
        //    },
        //    error: function (jqXHR, status, err) {
        //        alert("une erreur c'est produit réessayer");
        //    }

             
        //});

    }

    
    

    function initMap() {
       Obj = hot;
       console.log("momoo" + Obj);
    
        // Map options
        var options = {
            zoom: 8,
            center: { lat: 42.3601, lng: -71.0589 }
        }

        // New map
        var map = new google.maps.Map(document.getElementById('map'), options);

        // Listen for click on map
        google.maps.event.addListener(map, 'click', function (event) {
            // Add marker
            addMarker({ coords: event.latLng });
        });

        /*
        // Add marker
        var marker = new google.maps.Marker({
          position:{lat:42.4668,lng:-70.9495},
          map:map,
          icon:'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png'
        });
  
        var infoWindow = new google.maps.InfoWindow({
          content:'<h1>Lynn MA</h1>'
        });
  
        marker.addListener('click', function(){
          infoWindow.open(map, marker);
        });
        */

            // Array of markers
            for (var i = 0; i < Obj.length; i++) {
                console.log(parseFloat(Obj[i].ing));
                console.log(parseFloat(Obj[i].lng));
                var mylat = parseFloat(Obj[i].ing);
                var mylng = parseFloat(Obj[i].lng);
                
                var latlng = { lat: mylat, lng: mylng };
                console.log("latlong" + latlng);
               

                var contentString = '<h1>Amesbury MA</h1>';

                var marker = new google.maps.Marker({
                    position: latlng,
                    
                    map: map,
                    //icon:props.iconImage
                });

                var infowindow = new google.maps.InfoWindow({
                    content: contentString
                });
                marker.addListener('click', function () {
                    infowindow.open(map, marker);
                });

               
        }
        
      
        
       
    }

    $.when(intialisation()).then(initMap());
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBbQXTYuOtVp_yKIrFaOSSHcVR-KY8omxM&callback=initMap">
</script>
<script>

    function recup() {

        var id = document.getElementById("details").value;
        console.log("okkkkkk" + id);
        document.location = "http://localhost:40740/Delivery/Details/" + id;

    }


    $(document).ready(function () {


        var colonnes = {};
        $("#contenu thead th").each(function (index, th) {
            colonnes[index] = $(th).text();
        }
        );

        // faire la recherche dans le tableau
        $("#search").keyup(function () {
            var mots = $(this).val().toLowerCase().split(" ");
            $("#contenu tbody tr").each(function (index, tr) {
                if (mots[0].length > 0) $(tr).hide(); else $(tr).show();
                $("td", tr).each(function (index, td) {
                    if (colonnes[index] in { 'Nom': true, 'Prenom': true, 'Etat': true, 'Ville': true }) {
                        for (mot in mots) {
                            if (mots[mot].length > 0 && $(td).text().toLowerCase().indexOf(mots[mot]) >= 0) {
                                $(tr).show();
                                return false;
                            }
                        }
                    }
                });
            });
        });

    });
</script>